# Exercise 2.B Cleaning up data

This notebook completes pages 17–18 of the Week 7 Lab Workbook.

## Import pandas

In [1]:
import pandas as pd

# Bringing pandas in so I can work with tables/DataFrames.

## Create / load the test data

In [2]:
# This is the same data from the last exercise.
# I am saving it as a CSV first so this notebook can run on its own.

test_data = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Name": ["Alicia", "Bob", "Charlie", "Dominic", "Eve", "Frank", "Grace", "Heidi"],
    "Age": [25, None, 22, 19, 31, 35, None, 18],
    "City": ["NY", "LA", "Chicago", "Houston", "Phoenix", "Boston", "Austin", "San Diego"],
    "Score": [85, 92, -1, 65, 78, None, 55, 90],
}

pd.DataFrame(test_data).to_csv("test_data.csv", index=False)

# Now I am reading the CSV file into a DataFrame named df.
df = pd.read_csv("test_data.csv")

# Checking the full DataFrame so I know the data loaded correctly.
df

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Column statistics

In [3]:
# describe() gives quick stats like count, mean, min, and max.
# This helps me spot missing values or weird numbers before cleaning.
df.describe()

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

In [4]:
# This shows only people older than 18.
# I used > 18 because the task says greater than 18, not equal to 18.
df[df["Age"] > 18]

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

In [5]:
# This keeps scores that are between 50 and 100.
# It helps remove scores that are too low, too high, or just not valid.
df[(df["Score"] > 50) & (df["Score"] < 100)]

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

In [6]:
# I am making a cleaned copy of df.
# The original df stays the same, and df_cleaned is the one I clean up.
# This drops rows where Score is less than 0 because negative scores do not make sense here.

df_cleaned = df.drop(df[df["Score"] < 0].index)

# Reviewing the cleaned DataFrame after removing the invalid score row.
df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [7]:
# Dropping the City column because the task says to remove it.
# axis=1 means I am dropping a column, not a row.

df_cleaned = df_cleaned.drop("City", axis=1)

# Checking that City is gone now.
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

In [8]:
# Filling in missing Age values with the average Age.
# This is useful because it keeps the rows instead of deleting them.

mean_age = df_cleaned["Age"].mean()
df_cleaned["Age"] = df_cleaned["Age"].fillna(mean_age)

# Checking the DataFrame to make sure the missing Ages are filled in.
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [9]:
# Replacing missing Score values with the average Score.
# This is another way to handle missing data without losing the whole row.

mean_score = df_cleaned["Score"].mean()
df_cleaned["Score"] = df_cleaned["Score"].replace(pd.NA, mean_score)

# Since pandas may read missing numbers as NaN, this makes sure all missing scores are filled.
df_cleaned["Score"] = df_cleaned["Score"].fillna(mean_score)

# Checking the DataFrame after replacing the missing Score.
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0   77.5
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [10]:
# dropna() removes rows that still have missing values.
# At this point, there should not be any left, but I am checking/cleaning anyway.

df_cleaned = df_cleaned.dropna()

# Reviewing the DataFrame after removing any leftover NaN values.
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0   77.5
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [11]:
# Setting ID as the index because ID works like a unique label for each row.
# Then I remove the ID column from the regular columns.

df_cleaned = df_cleaned.set_index("ID")

# Final review of the cleaned DataFrame.
df_cleaned

       Name   Age  Score
ID
1    Alicia  25.0   85.0
2       Bob  25.6   92.0
4   Dominic  19.0   65.0
5       Eve  31.0   78.0
6     Frank  35.0   77.5
7     Grace  25.6   55.0
8     Heidi  18.0   90.0

## Quick final notes

The main cleaning steps were: remove bad scores, remove a column we do not need, fill in missing numbers with averages, remove leftover missing values, and use ID as the row label.