# Exercise 2.C Working with multiple DataFrames

In [1]:
# Importing the tools I need for this exercise
import numpy as np
import pandas as pd

## Basic Aggregations

In [2]:
# This is the starting sales data for the exercise.
# Each row shows a product, region, units sold, and price
sales_data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

# Turning the dictionary into a DataFrame so it looks like a small table.
df_sales = pd.DataFrame(sales_data)

df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [3]:
# Revenue is units sold times price
# This adds a new column so I can see how much money each row made.
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']

df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [4]:
# This gives the total units sold and total revenue for the whole DataFrame.
# Basically, it adds everything together across all products and regions.
total_units_sold = df_sales['Units_Sold'].sum()
total_revenue = df_sales['Revenue'].sum()

print(f"Total Units Sold: {total_units_sold}")
print(f"Total Revenue: ${total_revenue:,.2f}")

Total Units Sold: 105
Total Revenue: $16,000.00

In [5]:
# This finds the average units sold and average revenue.
# I am using mean() because it gives the average value.
average_units_sold = df_sales['Units_Sold'].mean()
average_revenue = df_sales['Revenue'].mean()

print(f"Average Units Sold: {average_units_sold:.2f}")
print(f"Average Revenue: ${average_revenue:,.2f}")

Average Units Sold: 11.67
Average Revenue: $1,777.78

## Grouping Data

In [6]:
# This groups the data by Product.
# It shows the total units sold and revenue for each product.
product_totals = df_sales.groupby('Product')[['Units_Sold', 'Revenue']].sum()

product_totals

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [7]:
# This groups the data by Region.
# It shows the average units sold and average revenue for each region.
region_averages = df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean()

region_averages

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [8]:
# This groups by Product and Region together.
# It helps me see the totals for each product in each region.
product_region_totals = df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum()

product_region_totals

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [9]:
# This sorts the rows from the lowest Units_Sold to the highest.
# Ascending means the smaller numbers show up first.
sorted_by_units = df_sales.sort_values(by='Units_Sold', ascending=True)

sorted_by_units

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [10]:
# This sorts the rows by Revenue from highest to lowest.
# I use descending order because I want to see the biggest revenue first
sorted_by_revenue = df_sales.sort_values(by='Revenue', ascending=False)

sorted_by_revenue

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [11]:
# This ranks each row based on Revenue.
# Rank 1 means that row made the most revenue.
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False)

df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

In [12]:
# This shows the DataFrame with the new Revenue_Rank column.
# Now I can quickly spot which rows performed the best.
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

## Merging DataFrames

In [13]:
# This is a second DataFrame with product category information.
# It connects each product letter to a category name.
product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}

df_products = pd.DataFrame(product_data)

df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [14]:
# This merges the sales DataFrame with the products DataFrame.
# They match together using the Product column.
df_merged = pd.merge(df_sales, df_products, on='Product')

df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

In [15]:
# Calling df_merged again so I can review the final merged table.
# This now includes sales info plus the product category.
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

In [16]:
# This groups the merged data by Category.
# It shows how much total revenue each category made.
category_revenue = df_merged.groupby('Category')['Revenue'].sum()

category_revenue

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64